import Foundation
import SwiftUI

/// A message in an Agent conversation.
struct AgentMessage: Identifiable {
    let id: UUID
    let role: Role
    var content: String
    let command: String?
    var thinking: String?
    var status: CommandStatus?
    var duration: TimeInterval?
    let timestamp: Date

    init(
        id: UUID = UUID(),
        role: Role,
        content: String,
        command: String? = nil,
        thinking: String? = nil,
        status: CommandStatus? = nil,
        duration: TimeInterval? = nil,
        timestamp: Date = Date()
    ) {
        self.id = id
        self.role = role
        self.content = content
        self.command = command
        self.thinking = thinking
        self.status = status
        self.duration = duration
        self.timestamp = timestamp
    }

    enum Role {
        case user
        case assistant
        case system
        case commandOutput
    }

    enum CommandStatus: String {
        case running
        case success
        case failed
        case blocked
        case skipped

        var icon: String {
            switch self {
            case .running: "circle.dotted"
            case .success: "checkmark.circle.fill"
            case .failed: "xmark.octagon.fill"
            case .blocked: "xmark.shield.fill"
            case .skipped: "hand.raised.fill"
            }
        }

        var color: Color {
            switch self {
            case .running: .blue
            case .success: .green
            case .failed: .red
            case .blocked: .gray
            case .skipped: .orange
            }
        }
    }

    enum AccessMode: String, CaseIterable, Identifiable, Sendable {
        case fullAccess = "fullAccess"  // Full access: routine commands run autonomously
        case supervised = "supervised"  // Supervised: medium-risk modifications need confirmation
        case readOnly = "readOnly"      // Read-only: inspection commands only

        var id: String { rawValue }

        var localizedName: String {
            switch self {
            case .fullAccess: L.t(.accessFull)
            case .supervised: L.t(.accessSupervised)
            case .readOnly: L.t(.accessReadonly)
            }
        }

        var shortName: String {
            switch self {
            case .fullAccess: L.t(.accessFullShort)
            case .supervised: L.t(.accessSupervisedShort)
            case .readOnly: L.t(.accessReadonlyShort)
            }
        }

        var icon: String {
            switch self {
            case .fullAccess: "bolt.shield.fill"
            case .supervised: "hand.raised.fill"
            case .readOnly: "lock.fill"
            }
        }

        var color: Color {
            switch self {
            case .fullAccess: .green
            case .supervised: .orange
            case .readOnly: .blue
            }
        }
    }

    /// Convert to AI API message format.
    func toAIMessages() -> [[String: String]] {
        switch role {
        case .user:
            return [["role": "user", "content": content]]
        case .assistant:
            var text = content
            if let thinking { text = "💭 \(thinking)\n\n\(text)" }
            if let command { text += "\n\nExecuting: `\(command)`" }
            return [["role": "assistant", "content": text]]
        case .commandOutput:
            return [["role": "user", "content": "Command output:\n```\n\(content)\n```"]]
        case .system:
            return [["role": "user", "content": "[System: \(content)]"]]
        }
    }
}

/// A command pending user confirmation.
struct PendingCommand: Identifiable {
    let id = UUID()
    let command: String
    let reason: String
    let riskLevel: RiskLevel
    /// Why this dialog appeared (e.g. "L2 · 首次确认"). Empty when unknown.
    /// Displayed verbatim by the confirmation banner.
    let reasonDetail: String
    let continuation: (Bool) -> Void

    init(
        command: String,
        reason: String,
        riskLevel: RiskLevel,
        reasonDetail: String = "",
        continuation: @escaping (Bool) -> Void
    ) {
        self.command = command
        self.reason = reason
        self.riskLevel = riskLevel
        self.reasonDetail = reasonDetail
        self.continuation = continuation
    }

    enum RiskLevel {
        case moderate
        case dangerous

        var icon: String {
            switch self {
            case .moderate: "exclamationmark.triangle"
            case .dangerous: "exclamationmark.octagon"
            }
        }

        var color: String {
            switch self {
            case .moderate: "orange"
            case .dangerous: "red"
            }
        }
    }
}

/// A plan generated by the AI before execution.
struct AgentPlan: Identifiable {
    let id = UUID()
    let thinking: String?
    let steps: [Step]
    let summary: String

    struct Step: Identifiable {
        let id = UUID()
        let description: String
        let command: String
        let riskLevel: CommandSafety

        var isAutoExecutable: Bool {
            riskLevel == .safe
        }

        /// Deterministic effect profile, computed on demand from the
        /// command text. Never supplied by the model — parse assigns
        /// riskLevel via CommandSafety, effect derives the same way.
        var effect: CommandEffectProfile {
            CommandEffectProfiler.profile(command: command)
        }
    }

    /// Steps that need user confirmation (moderate + dangerous).
    var pendingSteps: [Step] {
        steps.filter { !$0.isAutoExecutable && $0.riskLevel != .blocked }
    }

    /// True when the plan cannot execute anything: every step is blocked.
    /// Callers skip the approval UI for such plans — there is nothing
    /// the user could approve into existence.
    var isUnexecutable: Bool {
        !steps.isEmpty && steps.allSatisfy { $0.riskLevel == .blocked }
    }

    /// Steps that will auto-execute.
    var autoSteps: [Step] {
        steps.filter(\.isAutoExecutable)
    }
}

/// Result of executing a single plan step.
struct StepResult: Identifiable {
    let id = UUID()
    let step: AgentPlan.Step
    let output: String
    let success: Bool
    let duration: TimeInterval
}

/// Execution report after completing a plan.
struct ExecutionReport {
    let results: [StepResult]
    let totalTime: TimeInterval

    var successCount: Int {
        results.filter(\.success).count
    }

    var failureCount: Int {
        results.filter { !$0.success }.count
    }

    var totalCount: Int {
        results.count
    }
}

/// Timeout error for Agent operations.
struct TimeoutError: Error {}
