import Foundation
import SwiftUI

/// A message in an Agent conversation.
struct AgentMessage: Identifiable {
    let id: UUID
    let role: Role
    var content: String
    let command: String?
    var thinking: String?
    var status: CommandStatus?
    var duration: TimeInterval?
    let timestamp: Date

    init(
        id: UUID = UUID(),
        role: Role,
        content: String,
        command: String? = nil,
        thinking: String? = nil,
        status: CommandStatus? = nil,
        duration: TimeInterval? = nil,
        timestamp: Date = Date()
    ) {
        self.id = id
        self.role = role
        self.content = content
        self.command = command
        self.thinking = thinking
        self.status = status
        self.duration = duration
        self.timestamp = timestamp
    }

    enum Role {
        case user
        case assistant
        case system
        case commandOutput
    }

    enum CommandStatus: String {
        case running
        case success
        case failed
        case blocked
        case skipped

        var icon: String {
            switch self {
            case .running: "circle.dotted"
            case .success: "checkmark.circle.fill"
            case .failed: "xmark.octagon.fill"
            case .blocked: "xmark.shield.fill"
            case .skipped: "hand.raised.fill"
            }
        }

        var color: Color {
            switch self {
            case .running: .blue
            case .success: .green
            case .failed: .red
            case .blocked: .gray
            case .skipped: .orange
            }
        }
    }

    enum AccessMode: String, CaseIterable, Identifiable, Sendable {
        case fullAccess = "fullAccess"  // 完全访问：自动执行常规命令
        case supervised = "supervised"  // 逐步确认：中危修改命令需确认
        case readOnly = "readOnly"      // 只读模式：只允许只读检查

        var id: String { rawValue }

        var localizedName: String {
            switch self {
            case .fullAccess: "完全访问"
            case .supervised: "逐步确认"
            case .readOnly: "只读模式"
            }
        }

        var shortName: String {
            switch self {
            case .fullAccess: "完全访问"
            case .supervised: "逐步确认"
            case .readOnly: "只读"
            }
        }

        var icon: String {
            switch self {
            case .fullAccess: "bolt.shield.fill"
            case .supervised: "hand.raised.fill"
            case .readOnly: "lock.fill"
            }
        }

        var color: Color {
            switch self {
            case .fullAccess: .green
            case .supervised: .orange
            case .readOnly: .blue
            }
        }
    }

    /// Convert to AI API message format.
    func toAIMessages() -> [[String: String]] {
        switch role {
        case .user:
            return [["role": "user", "content": content]]
        case .assistant:
            var text = content
            if let thinking { text = "💭 \(thinking)\n\n\(text)" }
            if let command { text += "\n\nExecuting: `\(command)`" }
            return [["role": "assistant", "content": text]]
        case .commandOutput:
            return [["role": "user", "content": "Command output:\n```\n\(content)\n```"]]
        case .system:
            return [["role": "user", "content": "[System: \(content)]"]]
        }
    }
}

/// A command pending user confirmation.
struct PendingCommand: Identifiable {
    let id = UUID()
    let command: String
    let reason: String
    let riskLevel: RiskLevel
    let continuation: (Bool) -> Void

    enum RiskLevel {
        case moderate
        case dangerous

        var icon: String {
            switch self {
            case .moderate: "exclamationmark.triangle"
            case .dangerous: "exclamationmark.octagon"
            }
        }

        var color: String {
            switch self {
            case .moderate: "orange"
            case .dangerous: "red"
            }
        }
    }
}

/// A plan generated by the AI before execution.
struct AgentPlan: Identifiable {
    let id = UUID()
    let thinking: String?
    let steps: [Step]
    let summary: String

    struct Step: Identifiable {
        let id = UUID()
        let description: String
        let command: String
        let riskLevel: CommandSafety

        var isAutoExecutable: Bool {
            riskLevel == .safe
        }
    }

    /// Steps that need user confirmation (moderate + dangerous).
    var pendingSteps: [Step] {
        steps.filter { !$0.isAutoExecutable && $0.riskLevel != .blocked }
    }

    /// Steps that will auto-execute.
    var autoSteps: [Step] {
        steps.filter(\.isAutoExecutable)
    }
}

/// Result of executing a single plan step.
struct StepResult: Identifiable {
    let id = UUID()
    let step: AgentPlan.Step
    let output: String
    let success: Bool
    let duration: TimeInterval
}

/// Execution report after completing a plan.
struct ExecutionReport {
    let results: [StepResult]
    let totalTime: TimeInterval

    var successCount: Int {
        results.filter(\.success).count
    }

    var failureCount: Int {
        results.filter { !$0.success }.count
    }

    var totalCount: Int {
        results.count
    }
}

/// Timeout error for Agent operations.
struct TimeoutError: Error {}
