import Foundation

/// A message in an Agent conversation.
struct AgentMessage: Identifiable {
    let id = UUID()
    let role: Role
    let content: String
    let command: String?
    let thinking: String?
    let timestamp = Date()

    enum Role {
        case user
        case assistant
        case system
        case commandOutput
    }

    init(role: Role, content: String, command: String? = nil, thinking: String? = nil) {
        self.role = role
        self.content = content
        self.command = command
        self.thinking = thinking
    }

    /// Convert to AI API message format.
    func toAIMessages() -> [[String: String]] {
        switch role {
        case .user:
            return [["role": "user", "content": content]]
        case .assistant:
            var text = content
            if let thinking { text = "💭 \(thinking)\n\n\(text)" }
            if let command { text += "\n\nExecuting: `\(command)`" }
            return [["role": "assistant", "content": text]]
        case .commandOutput:
            return [["role": "user", "content": "Command output:\n```\n\(content)\n```"]]
        case .system:
            return [["role": "user", "content": "[System: \(content)]"]]
        }
    }
}

/// A command pending user confirmation.
struct PendingCommand: Identifiable {
    let id = UUID()
    let command: String
    let reason: String
    let riskLevel: RiskLevel
    let continuation: (Bool) -> Void

    enum RiskLevel {
        case moderate
        case dangerous

        var icon: String {
            switch self {
            case .moderate: "exclamationmark.triangle"
            case .dangerous: "exclamationmark.octagon"
            }
        }

        var color: String {
            switch self {
            case .moderate: "orange"
            case .dangerous: "red"
            }
        }
    }
}

/// A plan generated by the AI before execution.
struct AgentPlan: Identifiable {
    let id = UUID()
    let thinking: String?
    let steps: [Step]
    let summary: String

    struct Step: Identifiable {
        let id = UUID()
        let description: String
        let command: String
        let riskLevel: CommandSafety

        var isAutoExecutable: Bool {
            riskLevel == .safe
        }
    }

    /// Steps that need user confirmation (moderate + dangerous).
    var pendingSteps: [Step] {
        steps.filter { !$0.isAutoExecutable && $0.riskLevel != .blocked }
    }

    /// Steps that will auto-execute.
    var autoSteps: [Step] {
        steps.filter(\.isAutoExecutable)
    }
}

/// Result of executing a single plan step.
struct StepResult: Identifiable {
    let id = UUID()
    let step: AgentPlan.Step
    let output: String
    let success: Bool
    let duration: TimeInterval
}

/// Execution report after completing a plan.
struct ExecutionReport {
    let results: [StepResult]
    let totalTime: TimeInterval

    var successCount: Int {
        results.filter(\.success).count
    }

    var failureCount: Int {
        results.filter { !$0.success }.count
    }

    var totalCount: Int {
        results.count
    }
}

/// Timeout error for Agent operations.
struct TimeoutError: Error {}
