import Foundation

/// The schema as it stood at v2026.4.5, the last release before the
/// 2026-09-29 wipe.
///
/// This is a frozen record, not a live value. Comparing the production schema
/// against it is what turns "an entity silently disappeared" into a build
/// failure. On 2026-09-29 fifteen entity tables were dropped with no error at
/// any call site; the only reason that was ever diagnosable is that a frozen
/// copy of the incident existed to compare against.
///
/// ## How to change the schema
///
/// - **Adding** an entity: register it in `BonkStore.Schema` and in the
///   baseline below. Additive changes are safe.
/// - **Removing** an entity: this destroys user data. Record it in
///   `BonkStore.Schema.approvedEntityDeletions` with a reason, and remove it
///   from the baseline. This is deliberately two edits so the loss has to be
///   typed out.
///
/// The baseline is intentionally *not* auto-regenerated by the test. A gate
/// that rewrites its own expectations is not a gate.
enum StoreSchemaContract {
    /// v2026.4.5 production schema. Frozen 2026-09-30.
    static let baselineEntityNames: [String] = [
        "HostItem",
        "UserPreferences",
        "Credential",
        "HostGroup",
        "AIConversationRecord",
        "AIMessageRecord",
        "AIProviderRecord",
        "Snippet",
        "PortForward",
        "JumpHost",
        "InlineSuggestionRecord",
        "SSHBackendProfile",
        "TriggerRule",
        "LogProfile",
        "LogPatternRow",
    ]
}
